### ISSUE TITLE
Reproducing build

### ISSUE THREAD

**Issue by colms** [snikulov/ffmpeg_win_example#1]
Hi. I'm totally new to CMake and found this project which does what I want it to do. I have a couple of issues I was hoping you could help with.

First, when I clone or download the directory, the cmake directory exists but doesn't contain any of the .cmake files so I had to add those manually.

Then I downloaded the shared and dev 64-bit FFMPEG from https://ffmpeg.zeranoe.com/builds/. In your instructions, you say to "install anywhere on build machine". What do you mean by install? Just download?

I then ran cmd.exe and ran the following commands:
set INCLUDE=%INCLUDE%;C:\Users\jsmith\Downloads\ffmpeg-20161003-cced839-win64-dev\ffmpeg-20161003-cced839-win64-dev\include
set LIB=%LIB%;C:\Users\jsmith\Downloads\ffmpeg-20161003-cced839-win64-dev\ffmpeg-20161003-cced839-win64-dev\lib

I then created a "build" directory within "ffmpeg_win_example" and cd'ed into it.  I then ran:
cmake ..

I got the error saying FFMPEG not found. What am I doing incorrectly?

**Comment by snikulov** [comment]
When you clone repository you should use `--recurse-submodules` option to get submodules.

**Comment by snikulov** [comment]
Second, you should also download https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-20161003-cced839-win64-shared.zip and extract both files to same folder. For example `C:\FFMPEG`

Third, cmake by default on Windows generate 32 bit solutions, AFAIR. You should explicitly state 
`cmake .. -G"Visual Studio 14 2015 Win64"` (for MSVC 2015 64bit) , because you've downloaded 64 bit ffmpeg.
Please check `cmake --help` for other VC versions if you using other then version 2015.

**Comment by colms** [comment]
Holy crap. That worked. Here are all of the steps I took for anyone else who wants to reproduce it:

---

Download the "dev" and "shared" versions from (64 bit used in this example):
https://ffmpeg.zeranoe.com/builds/

Create an install directory (anywhere):
C:\ffmpeg

Copy the "bin" folder from the "shared" FFMPEG into "C:\ffmpeg".
Copy the "include" and "lib" folder from the "dev" FFMPEG into "C:\ffmpeg".
Add "C:\ffmpeg" to the system environment path.

Create directory for the git project (anywhere):
"C:\ffmpeg_win_example"

Open cmd.exe and cd into "C:\ffmpeg_win_example".
Run the following:
git clone --recurse-submodules https://github.com/snikulov/ffmpeg_win_example.git

Create a build directory for the cmake output:
"C:\ffmpeg_win_example\ffmpeg_win_example\build"

cd into "build" and run:
cmake .. -G"Visual Studio 14 2015 Win64"

Open the Visual Studio project that was built located:
"C:\ffmpeg_win_example\ffmpeg_win_example\build\vcffmpeg.sln"
Right-click the solution in the solution explorer and click "Build Solution".

---

Awesome. I was dreading this all weekend and you made it so easy with this repo and fast response. Thanks very much for your help.

**Comment by snikulov** [comment]
@colms You are welcome :)
Published full procedure to wiki https://github.com/snikulov/ffmpeg_win_example/wiki/Full-build-procedure
