### ISSUE TITLE
New FFmpeg CmakeList

### ISSUE THREAD

**Issue by dumyCq** [snikulov/ffmpeg_win_example#2]
I was trying to build a cmake connection with MSVC and FFmpeg through your setting through Cmake GUI. After I tell where is the FFmpeg, they still report errors.

CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find FFmpeg (missing: AVCODEC_LIBRARIES AVCODEC_INCLUDE_DIRS
  AVFORMAT_LIBRARIES AVFORMAT_INCLUDE_DIRS AVUTIL_LIBRARIES
  AVUTIL_INCLUDE_DIRS AVDEVICE_LIBRARIES AVDEVICE_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFFmpeg.cmake:148 (find_package_handle_standard_args)
  CMakeLists.txt:38 (find_package)

How can I fix it?

**Comment by snikulov** [comment]
@dumyCq It was long time ago :) I'm not working with Microsoft Windows nowadays.
Have you read the procedure from here https://github.com/snikulov/ffmpeg_win_example/wiki/Full-build-procedure  ?

Just guess - you've not downloaded dev package from https://ffmpeg.zeranoe.com/builds/win64/
and not placed it as procedure suggests.
